import Head from "next/head";
import Script from "next/script";
import Navigation from "./components/navigation";
import Table from "./components/Table";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></Script>
      <main>
        <Navigation></Navigation>
        <Table>
          
        </Table>
      </main>
    </div>
  );
}
